# Generated by Django 5.2.17 on 2026-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_method",
            field=models.CharField(
                choices=[
                    ("password", "Username and password"),
                    ("google", "Sign in with Google"),
                ],
                default="password",
                max_length=10,
            ),
        ),
    ]
