# Generated by Django 5.2.17 on 2026-08-13 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_backfill_auth_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth_method",
        ),
    ]
